### ISSUE TITLE
Reek Guard task insists on watching all subdirectories, even when instructed otherwise.

### ISSUE THREAD

**Issue by jdickey** [grantspeelman/guard-reek#8]
Versions:

Gem name | Version
-------- | -------
`guard-reek` | 1.0.2 |
`guard` | 2.14.0
`rake` | 12.0.0

Relevant extract from my `Guardfile`:

```ruby
guard 'reek' do
  watch(%r{^lib/(.+)\.rb$})
  watch('config.reek')
end
```

Analogous task in `Rakefile`:

```ruby
Reek::Rake::Task.new do |t|
  t.config_file = 'config.reek'
  t.source_files = 'lib/**/*.rb'
  t.reek_opts = '--sort-by smelliness --no-progress  -s'
end
```

Hilarity ensues: Reek *should not* inspect the `./gemsets` directory; it has been configured to inspect only `./lib`.

```
[1] guard(main)> .find lib test -name \*.rb | wc -l
       6
[2] guard(main)> .find gemsets -name \*.rb | wc -l
    3441
[3] guard(main)> reek
01:47:41 - INFO - Run Reek
01:47:41 - INFO - Guard::Reek is running on all files
01:47:41 - INFO - Guard::Reek running on all
Inspecting 3446 file(s):
.SS..SS.SSSSSSSSSSSSSSSSSSSSSSS..SSSSSSS.S.S.....S......SS..S...........................................SSSSSSSSSSSSSSSSSSSSSSS.S^C/usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ast-2.3.0/lib/ast/node.rb:66:in `hash': Interrupt
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ast-2.3.0/lib/ast/node.rb:66:in `initialize'
	from /Users/jeffdickey/src/conversagence/service_catalogue/v1/service_catalogue_uc_v1/gemsets/dev/gems/parser-2.3.3.1/lib/parser/builders/default.rb:1182:in `new'
	from /Users/jeffdickey/src/conversagence/service_catalogue/v1/service_catalogue_uc_v1/gemsets/dev/gems/parser-2.3.3.1/lib/parser/builders/default.rb:1182:in `n'
	from /Users/jeffdickey/src/conversagence/service_catalogue/v1/service_catalogue_uc_v1/gemsets/dev/gems/parser-2.3.3.1/lib/parser/builders/default.rb:608:in `arg'
	from /Users/jeffdickey/src/conversagence/service_catalogue/v1/service_catalogue_uc_v1/gemsets/dev/gems/parser-2.3.3.1/lib/parser/ruby23.rb:6276:in `_reduce_526'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/racc/parser.rb:259:in `_racc_do_parse_c'
	from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/racc/parser.rb:259:in `do_parse'
	from /Users/jeffdickey/src/conversagence/service_catalogue/v1/service_catalogue_uc_v1/gemsets/dev/gems/parser-2.3.3.1/lib/parser/base.rb:162:in `parse'
	from /Users/jeffdickey/src/conversagence/service_catalogue/v1/service_catalogue_uc_v1/gemsets/dev/gems/parser-2.3.3.1/lib/parser/base.rb:179:in `parse_with_comments'
	from /Users/jeffdickey/src/conversagence/service_catalogue/v1/service_catalogue_uc_v1/gemsets/dev/gems/parser-2.3.3.1/lib/parser/base.rb:50:in `parse_with_comments'
	from /Users/jeffdickey/src/conversagence/service_catalogue/v1/service_catalogue_uc_v1/gemsets/dev/gems/reek-4.5.2/lib/reek/source/source_code.rb:88:in `syntax_tree'
	from /Users/jeffdickey/src/conversagence/service_catalogue/v1/service_catalogue_uc_v1/gemsets/dev/gems/reek-4.5.2/lib/reek/examiner.rb:138:in `syntax_tree'
	from /Users/jeffdickey/src/conversagence/service_catalogue/v1/service_catalogue_uc_v1/gemsets/dev/gems/reek-4.5.2/lib/reek/examiner.rb:120:in `run'
	from /Users/jeffdickey/src/conversagence/service_catalogue/v1/service_catalogue_uc_v1/gemsets/dev/gems/reek-4.5.2/lib/reek/examiner.rb:87:in `smells'
	from /Users/jeffdickey/src/conversagence/service_catalogue/v1/service_catalogue_uc_v1/gemsets/dev/gems/reek-4.5.2/lib/reek/examiner.rb:103:in `smelly?'
	from /Users/jeffdickey/src/conversagence/service_catalogue/v1/service_catalogue_uc_v1/gemsets/dev/gems/reek-4.5.2/lib/reek/report/formatter/progress_formatter.rb:43:in `progress'
	from /Users/jeffdickey/src/conversagence/service_catalogue/v1/service_catalogue_uc_v1/gemsets/dev/gems/reek-4.5.2/lib/reek/report/text_report.rb:21:in `add_examiner'
	from /Users/jeffdickey/src/conversagence/service_catalogue/v1/service_catalogue_uc_v1/gemsets/dev/gems/reek-4.5.2/lib/reek/cli/command/report_command.rb:24:in `block in populate_reporter_with_smells'
	from /Users/jeffdickey/src/conversagence/service_catalogue/v1/service_catalogue_uc_v1/gemsets/dev/gems/reek-4.5.2/lib/reek/cli/command/report_command.rb:23:in `each'
	from /Users/jeffdickey/src/conversagence/service_catalogue/v1/service_catalogue_uc_v1/gemsets/dev/gems/reek-4.5.2/lib/reek/cli/command/report_command.rb:23:in `populate_reporter_with_smells'
	from /Users/jeffdickey/src/conversagence/service_catalogue/v1/service_catalogue_uc_v1/gemsets/dev/gems/reek-4.5.2/lib/reek/cli/command/report_command.rb:15:in `execute'
	from /Users/jeffdickey/src/conversagence/service_catalogue/v1/service_catalogue_uc_v1/gemsets/dev/gems/reek-4.5.2/lib/reek/cli/application.rb:29:in `execute'
	from /Users/jeffdickey/src/conversagence/service_catalogue/v1/service_catalogue_uc_v1/gemsets/dev/gems/reek-4.5.2/bin/reek:13:in `<top (required)>'
	from /Users/jeffdickey/src/conversagence/service_catalogue/v1/service_catalogue_uc_v1/bin/reek:17:in `load'
	from /Users/jeffdickey/src/conversagence/service_catalogue/v1/service_catalogue_uc_v1/bin/reek:17:in `<main>'
[1] guard(main)> 
[1] guard(main)> 
```

**Comment by grantspeelman** [comment]
@jdickey I'll see if I can figure this out
looking at https://github.com/troessner/reek#configuration-file might help

**Comment by jdickey** [comment]
Thanks!

**Comment by grantspeelman** [comment]
What version of `reek` are you using?

**Comment by jdickey** [comment]
Reek 4.5.6 at the moment; IIRC 4.5.3 was current when I opened the issue.

**Comment by grantspeelman** [comment]
ok so basically currently we don't have an option the allows you to set the source_files like in done in your rake task. A`cmd` option like in **guard-rspec** or a `cli` option like in **guard-rubocop** could possible allow for something like that.

So currently you best bet to get a similar setup would be to add an exclude to you `config.reek`
```yaml
exclude_paths:
  - gemsets
```

Hope that helps

**Comment by jdickey** [comment]
Thanks again!

**Comment by grantspeelman** [comment]
Added some additional options https://github.com/grantspeelman/guard-reek#options :)
So hopefully you can get your setup closer to your rake task with something like this:

```ruby
guard 'reek', all: 'lib/**/*.rb', cli: '--sort-by smelliness --no-progress  -s' do
  watch(%r{^lib/(.+)\.rb$})
  watch('config.reek')
end
```
